### ISSUE TITLE
Update this plugin fam!!!

### ISSUE THREAD

**Issue by Preciousomonze** [Preciousomonze/woocommerce-phone-validator#4]
Update itt!!!😭😭😭😭
I didn’t expect more active installs actually, i felt it was an insignificant plugin, turned out to be quite useful, weirdd 🤡
Anyways, i have no choice than to keep working on it, being the #CodeXplorer, i can’t backdown. 
My way of the ninja 🤾🏽‍♂️
![image](https://user-images.githubusercontent.com/15174834/83922570-6fb0e700-a778-11ea-8193-49202838e021.jpeg)

So, See you soon!

**Comment by geektutor** [comment]
You are talking to yourself?

**Comment by Preciousomonze** [comment]
Yes dear![image](https://user-images.githubusercontent.com/15174834/87980150-02100e80-cacb-11ea-9c07-e92f1bcd3b2f.jpeg)
