### ISSUE TITLE
conflict with some themes (JS error - Uncaught SyntaxError)

### ISSUE THREAD

**Issue by rwkyyy** [Preciousomonze/woocommerce-phone-validator#40]
Hi there,

I found two themes that do not like this plugin, one of whom si Hello Elementor (lite elementor theme).

Both have this error in the console:
```
frontend.min.js?ver=1.3.0:1 Uncaught SyntaxError: Identifier '$' has already been declared
    at frontend.min.js?ver=1.3.0:1


```
Any suggestions on how to fix this?

Thank you!

**Comment by Preciousomonze** [comment]
Hello @rwkyyy , so sorry i've not been active here, loaded with lots of stuff. Not sure when i'll be free to get back on this project(didn't believe it'll get any downloads 😅).
Let me see if i can send a snippet, incase you still need it, seeing it's over 2 months already 😓

**Comment by rwkyyy** [comment]
@Preciousomonze hello, it's OK, I didn't had the time to debug it either, or I would have made a pull request or something.

Leave the snippet, hopefully it will help

**Comment by Preciousomonze** [comment]
@rwkyyy here's a link to the gist that should fix this: https://gist.github.com/Preciousomonze/807168b53a53e4d7f07593659e8ebb23

Please test on your staging site first, cause i didn't test it, but that should do the trick, let me know if you have any issues, or if it fixed it.

replace the js files in `assets/js/` respectively.

**Comment by rwkyyy** [comment]
Solved the error, but looks like on this case the validation doesn't work anymore, only if you input and then refresh the page, that is very odd.

**Comment by Preciousomonze** [comment]
Weird, since you know how to code.
Just go back to the previous default js file
Then comment out the part that declares the $ variable.
That should fix your issue.
Dont forget to also edit the min file

**Comment by rwkyyy** [comment]
@Preciousomonze sorry for the late reply, the updated gist worked just fine, but you have some spaces on Lines [93 & 96](https://gist.github.com/Preciousomonze/807168b53a53e4d7f07593659e8ebb23#file-frontend-js-L96) in the `<input>`, this caused the error to be dumped in the bottom of the page.

After fixing that everything is working fine.
